name: Deploy React App to Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Deploy to the Server (${{ github.event.inputs.environment }})
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e  # Stop on any error

            ENV=${{ github.event.inputs.environment }}

            if [ "$ENV" == "prod" ]; then
              echo "Deploying to production..."
              WORK_DIR=${{ secrets.PROD_SERVER_DEPLOYMENT_PATH }}
            else
              echo "Deploying to development..."
              WORK_DIR=${{ secrets.DEV_SERVER_DEPLOYMENT_PATH }}
            fi

            echo "Working directory: $WORK_DIR"

            cd "$WORK_DIR"

            # Backup .env if it exists
            if [ -f ".env" ]; then
              echo "Backing up .env"
              cp .env /tmp/.env.backup
            fi

            # Remove everything except .env
            find . -mindepth 1 -maxdepth 1 ! -name '.env' -exec rm -rf {} +

            # Re-init repo fresh
            git init
            git remote add origin ${{ github.repositoryUrl }}
            git fetch origin ${{ github.ref_name }}
            git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}

            # Restore .env
            if [ -f /tmp/.env.backup ]; then
              echo "Restoring .env"
              mv /tmp/.env.backup .env
            fi

            # Set up Node.js environment (adjust path if needed)
            export PATH=$HOME/.nvm/versions/node/v18.17.1/bin:$PATH

            # Install dependencies and build
            npm ci
            npm run build